'use client';
import { useState } from 'react';

export default function ReportsPage() {
  const [activeTab, setActiveTab] = useState<'charts' | 'reports'>('charts');
  
  const charts = [
    { 
        name: 'Archetype Distribution', 
        file: 'archetype_distribution.html',
        description: 'This chart breaks down all the complaints we collected to show which problems happen the most often. When you look at the bars, you can easily see that "Album Fragmentation" (people struggling to organize their albums) and "Volume Overwhelm" (having way too many photos to sort through) are the biggest headaches for our users by a wide margin.'
    },
    { 
        name: 'Cues vs Gaps', 
        file: 'cues_vs_gaps.html',
        description: 'When people try to find an old photo, they usually remember what it looked like (Visual) or when it happened (Temporal). This chart compares the things people remember against where the app actually fails them. The big takeaway here is that even though people rely heavily on visual memory, the app\'s visual search still leaves a massive gap in helping them find what they want.'
    },
    { 
        name: 'Frustration by Source', 
        file: 'frustration_by_source.html',
        description: 'We pulled feedback from App Store reviews and Google Support Forums. This chart measures how angry or frustrated users were on each platform. Interestingly, people posting on the Support Forums are the most frustrated—likely because they only go there when the app is completely broken for them and they are desperate for help.'
    },
    { 
        name: 'Impact Frequency Quadrant', 
        file: 'impact_frequency_quadrant.html',
        description: 'This is our priority map! It plots every problem based on how often it happens (left to right) and how much pain it causes the user (bottom to top). The top-right corner is the "danger zone"—problems here happen all the time and cause extreme frustration. These are the critical issues we need to fix first.'
    },
    { 
        name: 'Memory Cue Heatmap', 
        file: 'memory_cue_heatmap.html',
        description: 'This colorful map shows how people search for different types of photos. The darker the color, the stronger the connection. For example, you can see a very dark connection between "Event" photos and "Time/Date" searches. This tells us that when people look for event photos, they almost always try to search by the date it happened.'
    },
    { 
        name: 'Search Strategy Sankey', 
        file: 'search_strategy_sankey.html',
        description: 'This flowing diagram tracks a user\'s journey from the moment they start searching to what they do next. It shows a sad truth: a massive number of users who start by typing a keyword end up failing, giving up, or resorting to endlessly scrolling through their entire timeline by hand to find a single photo.'
    },
    { 
        name: 'Source Coverage', 
        file: 'source_coverage.html',
        description: 'This simply shows where all our data came from. The vast majority of the feedback we analyzed came directly from the Google Play Store. However, keep in mind that Play Store reviews are usually very short, while Support forum posts give us much deeper, detailed stories.'
    },
    { 
        name: 'Theme Clusters UMAP', 
        file: 'theme_clusters_umap.html',
        description: 'Our AI read through thousands of reviews and automatically grouped similar complaints together to form this map. Each dot is a piece of feedback. The big dense cluster you see forming around "Albums & Organization" proves that organizing photos is a totally separate, massive problem compared to just searching for them.'
    },
    { 
        name: 'User Sentiment Breakdown', 
        file: 'sentiment_analysis.html',
        description: 'An analysis of user sentiment parsed directly from the feedback text. This chart gives a broad overview of the emotional state of the users when describing their issues.'
    },
    { 
        name: 'Common Themes Word Cloud', 
        file: 'word_cloud.html',
        description: 'A visual representation of the most frequently used words in user feedback. Larger words indicate higher frequency, providing a quick glance at the most prominent keywords mentioned across all platforms.'
    }
  ];

  return (
    <div>
      <div className="hero" style={{ marginBottom: 'var(--space-xl)' }}>
        <div>
          <h1 className="hero__title">Outcomes Reports & Charts</h1>
          <p className="hero__subtitle">Original visualizations and deep-dive reports generated by the backend AI analysis pipeline</p>
        </div>
      </div>

      <div style={{ display: 'flex', gap: 'var(--space-md)', marginBottom: 'var(--space-2xl)', borderBottom: '1px solid var(--md-outline-variant)', paddingBottom: '0' }}>
        <button 
          onClick={() => setActiveTab('charts')}
          style={{
            background: 'none',
            border: 'none',
            padding: 'var(--space-sm) var(--space-md)',
            fontSize: '1.1rem',
            fontWeight: activeTab === 'charts' ? 600 : 400,
            color: activeTab === 'charts' ? 'var(--md-primary)' : 'var(--md-on-surface-variant)',
            borderBottom: activeTab === 'charts' ? '3px solid var(--md-primary)' : '3px solid transparent',
            cursor: 'pointer',
            transition: 'all 0.2s',
            marginBottom: '-1px'
          }}
        >
          Interactive Charts
        </button>
        <button 
          onClick={() => setActiveTab('reports')}
          style={{
            background: 'none',
            border: 'none',
            padding: 'var(--space-sm) var(--space-md)',
            fontSize: '1.1rem',
            fontWeight: activeTab === 'reports' ? 600 : 400,
            color: activeTab === 'reports' ? 'var(--md-primary)' : 'var(--md-on-surface-variant)',
            borderBottom: activeTab === 'reports' ? '3px solid var(--md-primary)' : '3px solid transparent',
            cursor: 'pointer',
            transition: 'all 0.2s',
            marginBottom: '-1px'
          }}
        >
          Detailed Reports
        </button>
      </div>

      {activeTab === 'charts' && (
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(600px, 1fr))',
          gap: 'var(--space-xl)',
          marginBottom: 'var(--space-2xl)'
        }}>
          {charts.map((chart) => (
            <div key={chart.file} style={{
              background: 'var(--md-surface-container-low)',
              borderRadius: 'var(--radius-lg)',
              overflow: 'hidden',
              boxShadow: 'var(--shadow-sm)',
              display: 'flex',
              flexDirection: 'column'
            }}>
              <div style={{ padding: 'var(--space-lg) var(--space-xl)', borderBottom: '1px solid var(--md-outline-variant)' }}>
                <h3 style={{ margin: '0 0 var(--space-xs) 0' }}>{chart.name}</h3>
                <p style={{ margin: 0, fontSize: '0.95rem', lineHeight: '1.5', color: 'var(--md-on-surface-variant)' }}>
                  {chart.description}
                </p>
              </div>
              <iframe 
                src={`/charts/${chart.file}`}
                style={{ width: '100%', height: '500px', border: 'none', background: 'white' }}
                title={chart.name}
              />
            </div>
          ))}
        </div>
      )}
      
      {activeTab === 'reports' && (
        <div style={{
          background: 'var(--md-surface-container-low)',
          borderRadius: 'var(--radius-lg)',
          padding: 'var(--space-xl)',
          boxShadow: 'var(--shadow-sm)',
          maxWidth: '800px'
        }}>
          <h2>Detailed Markdown Reports</h2>
          <p style={{ color: 'var(--md-on-surface-variant)', marginTop: 'var(--space-sm)', marginBottom: 'var(--space-xl)' }}>
            These reports contain deep qualitative analysis, supporting evidence, and strategic prioritization models. Click to view the full formatted documents.
          </p>
          <ul style={{ listStyleType: 'none', padding: 0 }}>
            <li style={{ marginBottom: '16px', padding: '16px', border: '1px solid var(--md-outline-variant)', borderRadius: '8px' }}>
              <div style={{ fontSize: '1.1rem', marginBottom: '4px' }}>
                📄 <a href="/opportunity_matrix.html" target="_blank" style={{ color: 'var(--md-primary)', textDecoration: 'none', fontWeight: 600 }}>Opportunity Matrix Report</a>
              </div>
              <div style={{ color: 'var(--md-on-surface-variant)', fontSize: '0.9rem', paddingLeft: '28px' }}>Prioritized list of problem archetypes mapped against severity and frequency.</div>
            </li>
            <li style={{ marginBottom: '16px', padding: '16px', border: '1px solid var(--md-outline-variant)', borderRadius: '8px' }}>
              <div style={{ fontSize: '1.1rem', marginBottom: '4px' }}>
                📄 <a href="/archetype_report.html" target="_blank" style={{ color: 'var(--md-primary)', textDecoration: 'none', fontWeight: 600 }}>Archetype Deep-Dive Report</a>
              </div>
              <div style={{ color: 'var(--md-on-surface-variant)', fontSize: '0.9rem', paddingLeft: '28px' }}>Comprehensive analysis of each archetype including user quotes and behavior patterns.</div>
            </li>
            <li style={{ marginBottom: '16px', padding: '16px', border: '1px solid var(--md-outline-variant)', borderRadius: '8px' }}>
              <div style={{ fontSize: '1.1rem', marginBottom: '4px' }}>
                📄 <a href="/emergent_themes_report.html" target="_blank" style={{ color: 'var(--md-primary)', textDecoration: 'none', fontWeight: 600 }}>Emergent Themes Report</a>
              </div>
              <div style={{ color: 'var(--md-on-surface-variant)', fontSize: '0.9rem', paddingLeft: '28px' }}>High-level thematic analysis surfacing broader platform trends and gaps.</div>
            </li>
            <li style={{ padding: '16px', border: '1px solid var(--md-outline-variant)', borderRadius: '8px' }}>
              <div style={{ fontSize: '1.1rem', marginBottom: '4px' }}>
                📄 <a href="/memory_cue_analysis.html" target="_blank" style={{ color: 'var(--md-primary)', textDecoration: 'none', fontWeight: 600 }}>Memory Cue Analysis</a>
              </div>
              <div style={{ color: 'var(--md-on-surface-variant)', fontSize: '0.9rem', paddingLeft: '28px' }}>Study of how users attempt to retrieve photos based on emotional vs temporal cues.</div>
            </li>
          </ul>
        </div>
      )}
    </div>
  );
}
